const apps = [
  {
    id: 'fitxForm',
    title: 'Fitx Form',
    subheader: 'NPM Package',
    avatar: 'F',
    cardClass: 'cardRoot',
    avatarClass: 'avatar',
    cardMediaClass: 'media',
    image: '/public/images/jsontoform.png',
    imageTitle: 'Fitx Form',
    href: 'https://www.npmjs.com/package/fitx-form',
    cardContent: 'A responsive React form for various input types controlled by a JSON component for faster and easier web development.',
    paragraphs: [
      'Installation',
      'fitx-form is available as an npm package.',
      'npm install fitx-form',
      'It converts a given JSON input into a React Form',
    ],
  },
  {
    id: 'kiUi',
    title: 'Ki Ui',
    subheader: 'NPM Package',
    avatar: 'K',
    cardClass: 'cardRoot',
    avatarClass: 'avatar',
    cardMediaClass: 'media',
    image: '/public/images/kiui.png',
    imageTitle: 'Fitx Form',
    href: 'https://www.npmjs.com/package/ki-ui',
    cardContent: 'React based light weight ui components',
    paragraphs: [
      'Installation',
      'ki-ui is available as an npm package.',
      'npm install ki-ui',
      'The basic html light weighted elements are bundled to make the app very light',
    ],
  },
  {
    id: 'reactExpressBoilerplate',
    title: 'React Express Boilerplate',
    subheader: 'Git Repo',
    avatar: 'R',
    cardClass: 'cardRoot',
    avatarClass: 'avatar',
    cardMediaClass: 'media',
    image: '/public/images/react-boilerplate.png',
    imageTitle: 'React Express Boilerplate',
    href: 'https://github.com/RyderKishan/react-express-boilerplate',
    cardContent: 'Best boilerplate code for highly scalable applications',
    paragraphs: [
      'Clone the repo',
      'npm install - For packages',
      'npm start - To run the code',
      'npm test - For testing',
      `The boilerplate is production ready and can be deployed with in
      the docker containers. It uses express to serve the static files.
      All the config can be done via the env variables`,
    ],
  },
  {
    id: 'springServer',
    title: 'Springboot Boilerplate',
    subheader: 'Git Repo',
    avatar: 'S',
    cardClass: 'cardRoot',
    avatarClass: 'avatar',
    cardMediaClass: 'media',
    image: '/public/images/spring-boot.jpg',
    imageTitle: 'Springboot Boilerplate',
    href: 'https://github.com/RyderKishan/spring-server',
    cardContent: 'A basic spring boilerplate with all basic CRUD operations',
    paragraphs: [
      'Installation',
      'Clone the repo',
      'gradle build',
      'gradle bootRun',
    ],
  },
  {
    id: 'cssTricks',
    title: 'Css Tricks',
    subheader: 'Medium Article',
    avatar: 'M',
    cardClass: 'cardRoot',
    avatarClass: 'avatar',
    cardMediaClass: 'media',
    image: '/public/images/cssTricks.png',
    imageTitle: 'CSS Simple Style Guide',
    href: 'https://medium.com/@kishan020696/css-simple-style-guide-5f4d203d5ca0',
    cardContent: 'A simple guide that can be followed to achieve css alignments',
    paragraphs: [
      'It is a medium article',
      `It includes all the basic center alignment techniques
      A similar article on headers and footers can also be found in the list`,
    ],
  },
  {
    id: 'expressWebpack',
    title: 'React 16 with Webpack 4 and Babel 7',
    subheader: 'Medium Article',
    avatar: 'R',
    cardClass: 'cardRoot',
    avatarClass: 'avatar',
    cardMediaClass: 'media',
    image: '/public/images/expressWebpack.png',
    imageTitle: 'React 16 with Webpack 4 and Babel 7',
    href: 'https://medium.com/@kishan020696/react-16-with-webpack-4-and-babel-7-7befed102817',
    cardContent: 'A smalll write up on using the latest of reach with babel and webpack',
    paragraphs: [
      'It is a medium article',
      `All beginers can gain knowledge on react how it is rendered
      and how the package is bundled using webpack and convereted
      using babel`,
    ],
  },
];

const props = {};

export {
  props,
  apps,
};
